name: CI
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"
    types: [opened, synchronize]

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    if: (github.event.action != 'closed' || github.event.pull_request.merged == true)
    strategy:
      matrix:
        os: [ ubuntu-20.04, macos-11 ] # list of os: https://github.com/actions/virtual-environments
    runs-on: ${{ matrix.os }}
    steps:
        - uses: actions/setup-go@v3
          with:
            go-version: 1.18.x

        - name: Install dependencies on Linux
          if: runner.os == 'Linux'
          run: sudo apt update && sudo apt install build-essential

        - name: Golang-ci install
          if: runner.os == 'Linux'
          run: make lintci-deps

        - uses: actions/cache@v3
          with:
            path: |
              ~/.cache/go-build
              ~/Library/Caches/go-build
              ~/go/pkg/mod
            key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
            restore-keys: ${{ runner.os }}-go-

        - name: Lint
          if: runner.os == 'Linux'
          run: make lint
